In [2]:
import pandas as pd

2 main datatypes:
- series: array alike - 1-dimensional
- dataFrame: object alike - 2-dimensional

In [3]:
# Series
series = pd.Series(["BMW", "Toyota", "Honda"])
colors = pd.Series(["blue", "red", "green"])

In [4]:
series

0       BMW
1    Toyota
2     Honda
dtype: object

In [5]:
colors

0     blue
1      red
2    green
dtype: object

In [6]:
car = pd.DataFrame({"Manufacturer": series, "Color": colors})

In [7]:
car

  Manufacturer  Color
0          BMW   blue
1       Toyota    red
2        Honda  green

In [8]:
# Import data
car_sales = pd.read_csv("./49 - car-sales.csv")

In [9]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

## Anatomy of a DataFrame
![.](./49%20-%20pandas-anatomy-of-a-dataframe.png)

In [10]:
# Export a dataframe
car_sales.to_csv("exported-car-sales.csv", index=False)

In [11]:
exported_car_sales = pd.read_csv("exported-car-sales.csv")
exported_car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00