## Coverage
0. Workflow
1. Getting data ready
2. Choose the right estimator/algorithm for our problem
3. Fit the model/algorithm and use it to make predictions
4. Evaliating a model
5. Improve a model
6. Save and load a trained model
7. Putting it all together

### I. A complete workflow

#### 1. Getting the data ready

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

np.random.seed(42)

heart_disease = pd.read_csv("./data/heart-disease.csv")
heart_disease.head(5)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [3]:
# X: features matrix
X = heart_disease.drop("target", axis=1)
Y = heart_disease["target"]

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

#### 2. Choosing the right model

In [4]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()

clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

#### 3. Fit the model to the training data

In [5]:
clf.fit(X_train, Y_train)

RandomForestClassifier()

In [6]:
# Making predictions
clf.predict(X_test)

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [7]:
clf.predict(pd.DataFrame(X_test.iloc[0]).T)

array([0])

In [8]:
pd.DataFrame(X_test.iloc[0]).ndim

2

In [9]:
tr = pd.DataFrame(
        [
            63,1,3,145,233,1,0,150,0,2.3,0,0,1
        ],
        index=
        [
            "age",
            "sex",
            "cp",
            "trestbps",
            "chol",
            "fbs",
            "restecg",
            "thalach",
            "exang",
            "oldpeak",
            "slope",
            "ca",
            "thal"
        ]
)
tr.T

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63.0,1.0,3.0,145.0,233.0,1.0,0.0,150.0,0.0,2.3,0.0,0.0,1.0

In [10]:
clf.predict(tr.T)

array([1])

In [11]:
Y_preds = clf.predict(X_test)
Y_preds

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

#### 4. Evaluate the model on the training data and test data

In [12]:
# accuracy metric
clf.score(X_train, Y_train)

1.0

In [13]:
clf.score(X_test, Y_test)

0.8524590163934426

In [14]:
# other metrics
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(Y_test, Y_preds))

              precision    recall  f1-score   support

           0       0.86      0.83      0.84        29
           1       0.85      0.88      0.86        32

    accuracy                           0.85        61
   macro avg       0.85      0.85      0.85        61
weighted avg       0.85      0.85      0.85        61

In [15]:
confusion_matrix(Y_test, Y_preds)

array([[24,  5],
       [ 4, 28]])

In [16]:
accuracy_score(Y_test, Y_preds)

0.8524590163934426

#### 4. Enhance the model

In [17]:
# Try changing the n_estimators
for i in range(10, 110, 10):
    print(f"Model with {i} n_estimators")
    model = RandomForestClassifier(n_estimators=i)
    model.fit(X_train, Y_train)
    print(f"Accuracy: {model.score(X_test, Y_test) * 100:.2f}%")

Model with 10 n_estimators
Accuracy: 85.25%
Model with 20 n_estimators
Accuracy: 78.69%
Model with 30 n_estimators
Accuracy: 81.97%
Model with 40 n_estimators
Accuracy: 83.61%
Model with 50 n_estimators
Accuracy: 83.61%
Model with 60 n_estimators
Accuracy: 88.52%
Model with 70 n_estimators
Accuracy: 85.25%
Model with 80 n_estimators
Accuracy: 86.89%
Model with 90 n_estimators
Accuracy: 83.61%
Model with 100 n_estimators
Accuracy: 86.89%

#### 6. Save and load a model

In [18]:
import pickle
pickle.dump(clf, open("RFM_1.pkl", "wb"))

In [19]:
loaded_model = pickle.load(open("./RFM_1.pkl", "rb"))
loaded_model.score(X_test, Y_test)

0.8524590163934426

### II. Getting detailed

#### 1. Getting data ready 

3 main to do:
    1. Splot the data into features & labels (`X` & `Y`)
    2. Filling (Imputing) or disregarding missing values
    3. Convert non-numerical -> numerical (feature encoding)

In [61]:
heart_disease.head(3)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1

In [62]:
X = heart_disease.drop("target", axis=1)
Y = heart_disease["target"]

In [63]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

##### 1.1. Make sure they are numerical

In [64]:
car_sales = pd.read_csv("./data/car-sales-extended.csv")
car_sales.head(3)

    Make Colour  Odometer (KM)  Doors  Price
0  Honda  White          35431      4  15323
1    BMW   Blue         192714      5  19943
2  Honda  White          84714      4  28343

In [65]:
X = car_sales.drop("Price", axis=1)
Y = car_sales["Price"]
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

In [66]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
model.fit(X_train, Y_train)

ValueError: could not convert string to float: 'Toyota'

In [73]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]

encoder = OneHotEncoder()
transformer = ColumnTransformer(
    [("one-hot", encoder, categorical_features)],
    remainder="passthrough"
)

transformed_X = transformer.fit_transform(X)
pd.DataFrame(transformed_X)

      0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [ ]:
dummies = pd.get_dummies(X)
dummies

,Odometer (KM),Doors,Make_BMW,Make_Honda,Make_Nissan,Make_Toyota,Colour_Black,Colour_Blue,Colour_Green,Colour_Red,Colour_White
0,35431,4,False,True,False,False,False,False,False,False,True
1,192714,5,True,False,False,False,False,True,False,False,False
2,84714,4,False,True,False,False,False,False,False,False,True
3,154365,4,False,False,False,True,False,False,False,False,True
4,181577,3,False,False,True,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
995,35820,4,False,False,False,True,True,False,False,False,False
996,155144,3,False,False,True,False,False,False,False,False,True
997,66604,4,False,False,True,False,False,True,False,False,False
998,215883,4,False,True,False,False,False,False,False,False,True
999,248360,4,False,False,False,True,False,True,False,False,False

In [ ]:
transformed_X_train, transformed_X_test, Y_train, Y_test = train_test_split(transformed_X, Y, test_size=0.2)
model.fit(transformed_X_train, Y_train)

model.score(transformed_X_test, Y_test)

0.3303588484950536

In [ ]:
dummies_X_train, dummies_X_test, Y_train, Y_test = train_test_split(dummies, Y, test_size=0.2)

model.fit(dummies_X_train, Y_train)
model.score(dummies_X_test, Y_test)

0.1710129880292368

##### 1.2. Dealing with missing values
- FIll with some value (imputation)
- Remove the sames with missing data altogether

In [86]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
car_sales_missing = pd.read_csv("./data/car-sales-extended-missing-data.csv")
car_sales_missing.head(3)

    Make Colour  Odometer (KM)  Doors    Price
0  Honda  White        35431.0    4.0  15323.0
1    BMW   Blue       192714.0    5.0  19943.0
2  Honda  White        84714.0    4.0  28343.0

In [77]:
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [78]:
car_sales_missing["Doors"].value_counts()

Doors
4.0    811
5.0     75
3.0     64
Name: count, dtype: int64

Option 1: Fill mising data with Pandas

In [79]:
car_sales_missing["Make"] = car_sales_missing["Make"].fillna("missing")
car_sales_missing["Colour"] = car_sales_missing["Colour"].fillna("missing")
car_sales_missing["Odometer (KM)"] = car_sales_missing["Odometer (KM)"].fillna(car_sales_missing["Odometer (KM)"].mean())
car_sales_missing["Doors"] = car_sales_missing["Doors"].fillna(4)

# Drop the any col that have missing Price as this is what we need to predict on
car_sales_missing = car_sales_missing.dropna()

car_sales_missing.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [89]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split

X = car_sales_missing.drop("Price",axis=1)
Y = car_sales_missing["Price"]

categorical_features = ["Make", "Colour", "Doors"]

encoder = OneHotEncoder()

transformer = ColumnTransformer(
    [("one-hot", encoder, categorical_features)],
    remainder="passthrough"
)



X_transformed = transformer.fit_transform(X)
X_transformed.toarray()

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 2.48360e+05]], shape=(1000, 16))

Option 2: Fill mising data with sklearn

In [49]:
car_sales_missing = pd.read_csv("./data/car-sales-extended-missing-data.csv")

In [50]:
# Drop rows with missing price 
car_sales_missing = car_sales_missing.dropna(subset="Price")

In [51]:
# split data into training-testing sets before filling data
X = car_sales_missing.drop("Price", axis=1)
Y = car_sales_missing["Price"]

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

In [52]:
# create imputers
from sklearn.impute import SimpleImputer
# Categorial imputer
cat_imputer = SimpleImputer(strategy="constant", fill_value="missing")
# Doors imputer
doors_imputer = SimpleImputer(strategy="constant", fill_value=4)
# Odometer imputer
num_imputer = SimpleImputer(strategy="mean")

# Define columns to apply imputers to
cat_features = ["Make", "Colour"]
doors_features = ["Doors"]
num_features = ["Odometer (KM)"]

In [57]:
from sklearn.compose import ColumnTransformer
transformer = ColumnTransformer([
    ("cat_imputer", cat_imputer, cat_features),
    ("door_imputer", doors_imputer, doors_features),
    ("num_imputer", num_imputer, num_features)
], remainder="passthrough",
    sparse_threshold=0)

filled_X_train = pd.DataFrame(transformer.fit_transform(X_train), columns=["Make", "Colour", "Doors", "Odometer (KM)"])
filled_X_train.head(3)

      Make Colour Doors Odometer (KM)
0  missing   Blue   5.0       40774.0
1      BMW  White   5.0      195419.0
2    Honda  White   4.0       42844.0

In [58]:
filled_X_test = pd.DataFrame(transformer.fit_transform(X_test), columns=["Make", "Colour", "Doors", "Odometer (KM)"])
filled_X_test.head(3)

     Make Colour Doors Odometer (KM)
0  Toyota  Green   4.0      106475.0
1  Nissan  White   4.0      222917.0
2  Nissan  White   4.0      203795.0

In [59]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

one_hot_features = ["Make", "Colour"]

one_hot = OneHotEncoder()
tranformer = ColumnTransformer([("one_hot", one_hot, one_hot_features)],
                               remainder="passthrough",
                               sparse_threshold=0)

transformed_X_train = tranformer.fit_transform(filled_X_train)
transformed_X_test = tranformer.fit_transform(filled_X_test)

In [60]:
transformed_X_train

array([[0.0, 0.0, 0.0, ..., 0.0, 5.0, 40774.0],
       [1.0, 0.0, 0.0, ..., 0.0, 5.0, 195419.0],
       [0.0, 1.0, 0.0, ..., 0.0, 4.0, 42844.0],
       ...,
       [0.0, 0.0, 0.0, ..., 0.0, 4.0, 74919.0],
       [0.0, 0.0, 0.0, ..., 0.0, 4.0, 129454.0],
       [0.0, 1.0, 0.0, ..., 0.0, 4.0, 126854.0]],
      shape=(760, 13), dtype=object)

In [62]:
np.random.seed(42)
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(transformed_X_train, Y_train)

model.score(transformed_X_test, Y_test)

0.2639420469498037

### Choosing the correct model

![.](./data/sklearn-ml-map.png)

#### Regression Problem

In [65]:
# Get California Housing dataset
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()
print(housing)

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]], shape=(20640, 8)), 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894], shape=(20640,)), 'frame': None, 'target_names': ['MedHouseVal'], 'feature_names': ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude'], 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 20640\n\n:Number of Attributes: 8 numeric, predictive attributes and the target\n\n:Attribute Information:\n    - MedInc        median income in block group\n    - HouseAge      median house age in block group\n    - AveRooms      average number of rooms per household\n    - AveBedrms     average number of bedrooms per household\n    - Population    block group population\n    - AveOccup      average number of household members\n    - Latitude      block group latitude\n    - Longitude     block group longitude\n\n:Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib repository.\nhttps://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. rubric:: References\n\n- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n  Statistics and Probability Letters, 33:291-297, 1997.\n'}

In [ ]:
housingdf = pd.DataFrame(housing["data"], columns=housing["feature_names"])
housingdf["Price"] = housing["target"]
housingdf.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

In [ ]:
from sklearn.linear_model import Ridge
X = housingdf.drop("Price", axis=1)
Y = housingdf["Price"]

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

In [ ]:
model = Ridge()
model.fit(X_train, Y_train)

model.score(X_test, Y_test)

0.6072168840855614

In [80]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(X_train, Y_train)

model.score(X_test, Y_test)

0.8013964898609778